window.$ = window.jQuery = require('jquery');
require('popper.js')
require('bootstrap')
require('owl.carousel')
window.AOS = require('aos')
require('./jquery.sticky')
require('stickyfill')
require('jquery.easing')
require('jquery.fancybox')
require('./isotope.pkgd.min.js')
